/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package transaksi;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import restoran.main;

/**
 *
 * @author meita
 */
public class pembayaran extends javax.swing.JInternalFrame {

    /**
     * Creates new form pembayaran
     */
    public pembayaran() {
        initComponents();
        dibayar.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                if (dibayar.getText().length()>0){
                    kembali.setText(String.valueOf(Integer.parseInt(dibayar.getText()) - Integer.parseInt(total_pesanan.getText())));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (dibayar.getText().length()>0){
                    kembali.setText(String.valueOf(Integer.parseInt(dibayar.getText()) - Integer.parseInt(total_pesanan.getText())));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                if (dibayar.getText().length()>0){
                    kembali.setText(String.valueOf(Integer.parseInt(dibayar.getText()) - Integer.parseInt(total_pesanan.getText())));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        meja = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        total_pesanan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dibayar = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        kembali = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();

        setTitle("Transaksi Pembayaran");

        jLabel3.setText("No. Meja");

        meja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        meja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mejaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Total Pesanan");

        total_pesanan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        total_pesanan.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Dibayar");

        dibayar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        dibayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        dibayar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Kembali");

        kembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kembali.setText("0");

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total_pesanan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(dibayar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(meja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kembali))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(meja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(total_pesanan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dibayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kembali))
                .addGap(18, 18, 18)
                .addComponent(simpan)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariTotal(int noMeja){
        if (noMeja > 0){
            try {
                Class.forName ("com.mysql.jdbc.Driver");
                String urldb="jdbc:mysql://localhost:3306/restaurant";
                String user=main.dbUser;
                String password=main.dbPassword;
                Connection koneksi=java.sql.DriverManager.getConnection(urldb,user,password);
                String sql = "SELECT "
                            + "SUM(((detail_pesanan.jumlah)*(makanan.harga))) as total "
                            + "FROM "
                            + " detail_pesanan "
                            + " INNER JOIN makanan "
                            + "     ON (detail_pesanan.nama = makanan.nama) "
                            + " INNER JOIN pesanan "
                            + "     ON (pesanan.no_pesanan = detail_pesanan.no_pesanan) "
                            + "WHERE (pesanan.no_meja = "+noMeja+" and lunas = 0)";

                Statement st = koneksi.createStatement();
                ResultSet rs = st.executeQuery(sql);

                while (rs.next()){
                    total_pesanan.setText(rs.getString("total"));
                }
                rs.close();
                st.close();
                koneksi.close();
            }catch(ClassNotFoundException cnfe){
                System.out.println("kesalahan saat"+"me-load driver jdbc \n"+cnfe.getMessage());
            }catch(SQLException sqle){
                System.out.println("keslahan saat koneksi atau "+"kesalahan query sql \n"+sqle.getMessage());
            }   
        }
    }
    
    private void mejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mejaActionPerformed
        cariTotal(meja.getSelectedIndex()+1);
    }//GEN-LAST:event_mejaActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try {
            Class.forName ("com.mysql.jdbc.Driver");
            String urldb="jdbc:mysql://localhost:3306/restaurant";
            String user=main.dbUser;
            String password=main.dbPassword;
            Connection koneksi=java.sql.DriverManager.getConnection(urldb,user,password);
            String sql = "insert into `pembayaran`(`no_pesanan`,`dibayar`,`kembali`) "
                       + "values((select max(no_pesanan) from pesanan where lunas = 0 and no_meja = '"+(meja.getSelectedIndex()+1)+"'), "
                       + "       '"+dibayar.getText()+"', "
                       + "       '"+kembali.getText()+"')";

            Statement st = koneksi.createStatement();
            st.executeUpdate(sql);
    
            st.close();
            koneksi.close();
        }catch(ClassNotFoundException cnfe){
            System.out.println("kesalahan saat"+"me-load driver jdbc \n"+cnfe.getMessage());
        }catch(SQLException sqle){
            System.out.println("keslahan saat koneksi atau "+"kesalahan query sql \n"+sqle.getMessage());
        }   
    }//GEN-LAST:event_simpanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField dibayar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel kembali;
    private javax.swing.JComboBox meja;
    private javax.swing.JButton simpan;
    private javax.swing.JLabel total_pesanan;
    // End of variables declaration//GEN-END:variables
}
